# casty: a terminal web browser that drives headless Chromium over CDP and
# paints the page with the Kitty graphics protocol.  kitty-graphics.el runs it
# in `--embed` mode for `kitty-graphics-browse', which is how a tinymist
# preview is shown inside `emacs -nw' (see the Doom config's kitty section).
#
# cashmeredev's fork, not sanohiro/casty upstream: embed mode and the IPC
# socket kitty-graphics.el talks to exist only there.  Not in nixpkgs.
#
# No browser is bundled.  casty would otherwise download Chrome Headless Shell
# into ~/.casty on first run -- not something a Nix profile should do behind
# your back -- so the Doom config points it at the Chrome already installed
# (`kitty-graphics-casty-chrome', which sets CASTY_CHROME and skips the
# download).
{
  lib,
  buildNpmPackage,
  fetchFromGitHub,
}:

buildNpmPackage {
  pname = "casty";
  version = "1.2.2-unstable-2026-09-28";

  src = fetchFromGitHub {
    owner = "cashmeredev";
    repo = "casty";
    rev = "771c56b0988331b4d173968c4ba15e4d627a490f";
    hash = "sha256-23Od9mxVDKItiibBsYFg414v/6BDv+56RpTRq/1Ukhg=";
  };

  # casty's .gitignore excludes package-lock.json, so the repo has none and
  # buildNpmPackage has nothing to pin `ws' with.  This one was generated by
  # `npm install' at the rev above; its only dependency is ws 8.22.0.
  postPatch = ''
    cp ${./casty-package-lock.json} package-lock.json
  '';

  npmDepsHash = "sha256-1oklwkpbBlUZwq/3c7VdaEQsFzBNPpOyHZq91zL0bBg=";

  # Plain JavaScript; there is nothing to build, only `ws' to install.
  dontNpmBuild = true;

  meta = {
    description = "TTY web browser using raw CDP and the Kitty graphics protocol (embed-mode fork)";
    homepage = "https://github.com/cashmeredev/casty";
    license = lib.licenses.mit;
    mainProgram = "casty";
  };
}
