/*
  agenix recipient map. Read by the `agenix` CLI ONLY -- it is not part of any
  NixOS evaluation, is not a module, and nothing imports it. `agenix -e
  age/foo.age` looks for this file at the repo root, encrypts to every public
  key listed for that path, and re-encrypts on every edit.

  Everything here is PUBLIC key material. Committing it is the intended use.
  The matching private identities live at my.agenix.identityPaths, outside the
  flake, and must never be added -- the repo is public, and a git flake would
  copy them into the world-readable store besides.

  ADDING A HOST
    Every host needs ONE ed25519 key, and which kind depends on whether it runs
    sshd. Both are ordinary ed25519 keys; agenix accepts either as an identity.

      runs sshd   -> reuse /etc/ssh/ssh_host_ed25519_key. Nothing to generate,
                     nothing to back up. This is agenix's documented default.
                     victus-15.
      no sshd     -> generate a standalone one, as root:
                       umask 077 && mkdir -p /etc/agenix
                       ssh-keygen -t ed25519 -N "" -C agenix-identity \
                         -f /etc/agenix/identity-ed25519
                     galaxybook4-pro360, which does not run sshd and so has no
                     host key to encrypt to.

    Then put the .pub contents in the bindings below, add it to the recipient
    list of every secret that host must read, and re-key:

      agenix -r          # re-encrypt everything to the current lists

    THE TRADEOFF between the two is recovery, not security. A standalone key
    can be memorised -- `melt` encodes it as a 24-word BIP39 phrase -- while a
    host key is regenerated by a reinstall and is gone. So a host key is only
    appropriate where every secret it holds is re-derivable from somewhere
    else. See the victus15 binding for why that is true there and not on
    galaxybook.

  ONE IDENTITY PER HOST, NEVER SHARED
    Copying one private key to both machines would be simpler and is wrong.
    The ciphertext is in a PUBLIC repo, so any host holding the key can read
    any secret encrypted to it -- every per-secret list below would collapse to
    "both hosts" while still LOOKING scoped. Revocation would also become
    rotation: you could no longer drop a recipient and re-key.

  PER-SECRET RECIPIENTS, NOT ONE GLOBAL LIST
    A secret is readable by exactly the machines that need it. The remote
    builder key is the clearest case: it is what galaxybook uses to DISPATCH
    builds, so victus-15 -- the builder it dispatches TO -- has no reason to
    hold it, and a compromised builder should not be able to push work back.
*/

let
  # --- host identities -------------------------------------------------
  # Both are real now. Any host added later goes in as an obviously-invalid
  # placeholder until its key exists: agenix fails loudly on a malformed
  # recipient, which is far better than silently encrypting to a key nobody
  # holds.
  /*
    An ed25519 SSH key, not a native age one, and not a host key either.

    WHY NOT A NATIVE AGE KEY. An age identity can only be backed up as a file,
    and that file then has to reach a new machine before anything decrypts --
    the one bootstrap step nothing in this repo could automate. An ed25519 key
    round-trips through `melt` to a 24-word BIP39 seed phrase, so the identity
    is recoverable from words.

    That is NOT a passphrase. The words ENCODE the existing 256-bit key rather
    than deriving one from human-chosen input, so the search space stays the
    key's own. The distinction matters because these ciphertexts live in a
    PUBLIC repo: an attacker gets unlimited offline attempts, which a
    memorable passphrase would not survive.

    WHY NOT THE SSH HOST KEY, which is agenix's documented default: that
    presumes the host runs sshd, and galaxybook4-pro360 does not. A standalone
    key from `ssh-keygen` needs no sshd -- agenix accepts any ed25519 private
    key as an identity. The old note here rejected host keys specifically, not
    ed25519 keys.

    No passphrase on the key itself: activation is unattended and agenix
    cannot prompt. The seed phrase is the backup, not a second factor.
  */
  galaxybook = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIPRLwavNlS/Oa3RqYJhgoLetQTlp9JzU9+l9Via1sUQ agenix-identity";
  /*
    victus-15's SSH HOST KEY -- agenix's documented default, and available here
    for exactly the reason it was not on galaxybook: this host runs sshd
    (services.openssh.enable), so the keypair already exists and no new key
    material, backup or seed phrase enters the picture.

    NO melt seed phrase, deliberately, and the asymmetry is the point. A host
    key is regenerated by a reinstall and cannot be recovered from words, so it
    is only a sane identity for a machine whose secrets are all re-derivable
    from elsewhere -- which is true here: the password hashes also live on
    galaxybook, the signing key can be regenerated and re-trusted, and the
    tailscale key can be reissued. galaxybook holds the openvpn profile and the
    builder dispatch key, which are not, which is why it got the melt-able one.

    A SEPARATE KEY, not galaxybook's copied over. Sharing one identity would
    collapse every per-secret recipient list in this file into "both hosts",
    since the ciphertext is public -- and it would hand a compromised BUILDER
    the key it uses to dispatch builds to the laptop.
  */
  victus15 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJzOSdxCVOGM5cLeBc6pRC+0kmi2XCzx4UMfsAsDnR2Q root@nixos";

  allHosts = [
    galaxybook
    victus15
  ];
in
{
  /*
    Account password hashes.

    ONE FILE PER ACCOUNT, SHARED ACROSS HOSTS -- r0k0r's password is the same
    on every machine, so a per-host copy was two files that had to be kept
    identical by hand. features/users derives the /run/agenix path from the
    username, so the name here is load-bearing.

    r0k0r's hash goes to BOTH hosts -- one account, one password, one file.
    benjamin exists only on victus-15, so his goes to victus-15 alone; there is
    nothing on galaxybook that would ever read it.

    VERIFY BEFORE DELETING victus-15's untracked copies. This file carries
    galaxybook's hash. If the two machines had drifted, switching victus-15 to
    passwordSecret changes r0k0r's password there to galaxybook's -- silently,
    since a hash tells you nothing by looking at it. Compare
    /etc/nixos/secrets/victus-15-hashed-password-r0k0r against this plaintext
    first.

    victus-15 sets users.mutableUsers = false, where a hashedPasswordFile that
    never decrypts is an unloginnable machine and `passwd` cannot repair it.
    Prove decryption there BEFORE the switch that depends on it:

      sudo age -d -i /etc/ssh/ssh_host_ed25519_key age/hashed-password-r0k0r.age
  */
  "age/hashed-password-r0k0r.age".publicKeys = allHosts;
  "age/hashed-password-benjamin.age".publicKeys = [ victus15 ];

  # Gnus/auth-source credentials (netrc format: imap.gmail.com and
  # smtp.gmail.com lines for both accounts). Consumed by Emacs running as
  # r0k0r, so the secret needs owner = "r0k0r" where it is declared.
  "age/authinfo.age".publicKeys = [ galaxybook ];

  /*
    victus-15's TAILSCALE pre-auth key, read once by `tailscale up` and inert
    afterwards while the node stays authenticated. Its own file rather than a
    shared one: galaxybook joins the tailnet without a key file at all
    (services.tailscale.enable with no authKeyFile), so there is nothing to
    share.

    There is no entry here for features/headscale's authKeyFile. That feature
    talks to a self-hosted Headscale rather than to Tailscale's coordination
    server, and NEITHER host enables it -- an entry naming a file that does not
    exist makes `agenix -r` fail on every unrelated secret, so it stays out
    until something turns headscale on.
  */
  "age/tailscale-authkey-victus-15.age".publicKeys = [ victus15 ];

  /*
    victus-15's binary-cache SIGNING KEY -- my.nix-settings.signingKeySecret.
    Per host by definition: the public half is what peers put in
    trusted-public-keys, so the key's whole job is to say which store vouched
    for a path.
  */
  "age/nix-signing-key-victus-15.age".publicKeys = [ victus15 ];

  # OpenVPN profile, credentials inline -- features/openvpn/nixos.nix.
  "age/openvpn-profile.age".publicKeys = [ galaxybook ];

  # SSH private key the nix-daemon uses to dispatch remote builds.
  # galaxybook only: it is the client here, victus-15 is the builder.
  #
  # MIGRATE THIS LAST, and keep the existing tmpfiles-provisioned copy until
  # the agenix path is proven: it is the key that dispatches builds, so
  # breaking it costs the ability to rebuild remotely -- including the
  # rebuild that would fix it.
  "age/remote-builder-ssh-key.age".publicKeys = [ galaxybook victus15 ];
}
