{ lib }:

/*
  One feature's Hyprland Lua, kept as a real .lua file instead of a Nix string,
  so it can be edited with a Lua language server (see /.luarc.json).

    src     the feature's .lua file, installed as ~/.config/hypr/feat/<name>.lua
    values  what the Lua needs from Nix (store paths, options), rendered as
            ~/.config/hypr/nix/<name>.lua; the file reads it with
            `local nix = require("nix.<name>")`
    order   lib.mkBefore for features/hyprland, lib.mkAfter for every feature
            that contributes to it

  The generated hyprland.lua is then just the require lines, in the same order
  the old extraConfig strings were concatenated in (see the mkBefore note in
  features/hyprland/home.nix). Hyprland puts its config dir on package.path and
  re-runs require()'d files on reload, so nothing else changes at runtime.
*/
{ name, src, values ? { }, order ? lib.mkAfter }:
{
  xdg.configFile."hypr/feat/${name}.lua".source = src;
  xdg.configFile."hypr/nix/${name}.lua".text = ''
    -- Generated by Nix from features/${name}; read by feat/${name}.lua.
    return ${lib.generators.toLua { } values}
  '';
  wayland.windowManager.hyprland.extraConfig = order ''require("feat.${name}")'';
}
