# Originally generated by ‘nixos-generate-config’, since hand-corrected --
# regenerating it blindly will NOT reproduce this content, see below.
#
# The `/` UUID here used to be 473402c5-fb75-4760-afee-e10d2da78f5b, which is
# galaxybook4-pro360's root, not victus's. Everything else in this file had been
# adapted for victus (kvm-amd, rtsx_pci_sdmmc, amd microcode) -- only the root
# UUID was left behind, and `/boot` pointed at BCA2-7BE0, which matches neither
# machine. Switching victus onto this would have written an fstab and a
# systemd-boot entry referencing devices that do not exist: activation appears to
# succeed (/ and /boot are already mounted, so nothing remounts), then the next
# boot lands in an initrd emergency shell. Values below are verified against the
# live machine (`findmnt` + the running /etc/fstab, which agree).
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # btrfs label 'root', a TWO-device volume: devid 1 /dev/nvme0n1p2, devid 2 /dev/sda.
  # Both members report the same FSUUID, which is why lsblk shows it twice.
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9a16b001-1824-437a-ba2d-7f2b44fe0398";
      fsType = "btrfs";
    };

  # Mounted 0077, not the 0022 this file used to claim.
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DBA5-B63F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Present in the running system's fstab but declared nowhere in this tree --
  # dropped by 9756795 along with the UUID damage above. Without it a switch
  # silently removes /home from fstab (the live mount survives until reboot).
  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9a16b001-1824-437a-ba2d-7f2b44fe0398";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };
}
